[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "standard_morph"
version = "1.0.3"
description = "Standardizing morphologies"
readme = "README.md"
authors = [{ name = "Matthew Mallory", email = "matt.mallory@alleninstitute.org" }]
requires-python = ">=3.9"
license = "MIT"
dependencies = [
    "numpy",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "tests.*"]

[project.optional-dependencies]
soma-mip = ["imageio", "s3fs", "zarr", "scikit-image"]
ccf = ["pynrrd"]
full = ["imageio", "s3fs", "zarr", "scikit-image", "pynrrd"]
test = ["pytest", "pynrrd"]

[tool.setuptools.package-data]
"standard_morph" = ["*"]
"standard_morph.data" = ["*.nrrd"]

[project.urls]
Homepage = "https://github.com/AllenInstitute/standard_morph"

[tool.bumpversion]
current_version = "1.0.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["tests"]
